name: Compilar y generar APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Ejecutar la compilación de la aplicación
        run: ./gradlew assembleDebug

      - name: Subir el APK generado como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
