name: Automatizar envío de mensaje entre pantallas

on:
  push:
    branches:
      - master

jobs:
  testar-envio-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Descargar dependencias de UI Automator
        run: |
          sudo apt update
          sudo apt install -y android-tools-adb

      - name: Simular interacción entre pantallas
        run: |
          # Script de UI Automator para simular la interacción
          # Reemplazar "paquete.de.tu.app" con el nombre del paquete de tu aplicación
          # Reemplazar "MainActivity" con el nombre de la clase de la actividad principal
          # Reemplazar "Mensaje de prueba" con el mensaje que se desea enviar

          uiautomator2 run \
            -c "new UiAutomator2(new UiDevice()).newAppStartBuilder(\
            "paquete.de.tu.app").build().startActivity().waitForIdle();\
            new UiObject(new UiSelector().resourceId(\
            "paquete.de.tu.app:id/editTextMensaje")).setText(\
            "Mensaje de prueba");\
            new UiObject(new UiSelector().resourceId(\
            "paquete.de.tu.app:id/buttonEnviar")).click();\
            new UiObject(new UiSelector().resourceId(\
            "paquete.de.tu.app:id/textViewMensajeRecibido")).getText();"

      - name: Validar recepción del mensaje
        run: |
          # Verificar si el mensaje se recibió correctamente
          # Reemplazar "Mensaje de prueba" con el mensaje que se desea enviar

          if [[ "$(cat output.txt)" == "Mensaje de prueba" ]]; then
            echo "**Éxito:** El mensaje se recibió correctamente."
          else
            echo "**ERROR:** El mensaje no se recibió correctamente."
            exit 1
          fi

  validar-mensaje-recibido:
    runs-on: ubuntu-latest
    needs: testar-envio-mensaje
    steps:
      - name: Generar informe de éxito
        if: success()
        run: echo "**Informe de éxito:** El mensaje se recibió correctamente." > informe.txt

      - name: Generar informe de error
        if: failure()
        run: echo "**Informe de error:** El mensaje no se recibió correctamente." > informe.txt
