name: Verificar mensaje enviado en la app de Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verificar-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Ejecutar pruebas de la app de Android
        run: |
          # Compilar y ejecutar las pruebas de la app de Android
          ./gradlew test

      - name: Extraer el mensaje enviado en la app
        run: |
          # Extraer el mensaje enviado desde el logcat de la app de Android
          mensaje=$(adb logcat -d | grep "Mensaje enviado:" | cut -d ":" -f 2 | xargs)
          echo "Mensaje enviado desde la app de Android: $mensaje"

      - name: Verificar si el mensaje es correcto
        run: |
          # Verificar si el mensaje coincide con el esperado
          mensaje_esperado="Mensaje de prueba"
          if [ "$mensaje" == "$mensaje_esperado" ]; then
            echo "El mensaje enviado desde la app de Android es correcto: $mensaje"
          else
            echo "ERROR: El mensaje enviado desde la app de Android no es correcto. Se esperaba '$mensaje_esperado' pero se recibió '$mensaje'."
            exit 1
          fi
