name: Enviar mensaje de pantalla a pantalla

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  enviar-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje
        run: |
          # Simular envío de mensaje de una pantalla a otra
          mensaje="Hola desde la pantalla 1"
          echo "Mensaje enviado: $mensaje"

      - name: Mostrar mensaje recibido
        run: echo "Mensaje recibido en la pantalla 2"
