name: Enviar mensaje de pantalla a pantalla

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  enviar-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Ejecutar script de envío de mensaje
        run: |
          # Compilar la aplicación (reemplaza con tu comando de compilación)
          ./gradlew assembleDebug

          # Simular el envío de mensaje de una pantalla a otra
          adb shell am start -n "com.example.myapp/.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
          adb shell am broadcast -a com.example.myapp.ACTION_SEND_MESSAGE --es mensaje "Hola desde la pantalla 1"

      - name: Mostrar mensaje recibido
        run: |
          # Esperar unos segundos para que se procese el mensaje
          sleep 5

          # Leer el mensaje recibido desde la pantalla 2 (reemplaza con tu implementación)
          mensaje_recibido=$(adb logcat -d | grep "Mensaje recibido:")
          echo "Mensaje recibido en la pantalla 2: $mensaje_recibido"
